# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: macos-latest
    timeout-minutes: 30

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Flutter
      uses: subosito/flutter-action@v1.3.2

    - name: Install dependencies
      run: flutter pub get
          
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2.6.1
      with:
        api-level: 29
        target: default
        arch: x86_64
        script: flutter drive --target=test_driver/app.dart


